name: CI Pipeline
# # I Hope im lucky with this crap code
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Linting (Basic Check)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Linter
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8 (Basic Check)
        run: flake8 app tests --ignore=E501 --count --statistics
        # E501 (line too long) is ignored to keep things relaxed

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint  # Linting must pass, but it's lenient

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
          FLASK_ENV: testing
          SECRET_KEY: test-key
          PYTHONPATH: ${{ github.workspace }}
        run: pytest tests/
