name: CI Pipeline
# # I Hope im lucky with this crap code
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-errors:
    name: Code Error Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Run Pylint (Error Check Only)
        run: pylint --disable=all --enable=E app tests

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: check-errors

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
          FLASK_ENV: testing
          SECRET_KEY: test-key
          PYTHONPATH: ${{ github.workspace }}
        run: pytest tests/

  docker-build:
    name: Docker Build Check
    runs-on: ubuntu-latest
    needs: [check-errors, test]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build .
